---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-dry-run
    image: plugins/docker
    settings:
      repo: techknowlogick/caddy-s3browser
      dry_run: true
    when:
      event:
      - pull_request

  - name: create-test-bucket
    image: minio/mc:RELEASE.2020-04-04T05-28-55Z
    commands:
    - sleep 4 # hope that minio has started by this point
    - mc config host add test http://objectstorage:9000 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    - mc ls test
    - mc mb test/s3browser-test
    - echo "test file 1" > test/main.txt
    - echo "test file 12" > test/one.txt
    - echo "test file 123" > test/second.txt
    - echo "test file 1234" > test/another.txt
    - echo "test file 12345" > test/last.txt
    - mc policy set download test/s3browser-test
    - mc cp ./s3-customize-test.json test/s3browser-test/.s3-customize.json
    - mc cp ./test/main.txt test/s3browser-test
    - mc cp ./test/second.txt test/s3browser-test
    - mc cp ./test/one.txt test/s3browser-test/one/
    - mc cp ./test/another.txt test/s3browser-test/one/
    #- mc mb test/s3browser-test/one/two/
    #- mc mb test/s3browser-test/one/two/three/
    #- mc mb test/s3browser-test/one/two/three/four/
    #- mc cp ./test/another.txt test/s3browser-test/one/two
    #- mc cp ./test/another.txt test/s3browser-test/one/two/three
    - mc cp ./test/last.txt test/s3browser-test/one/two/three/four/
    #- mc rm test/s3browser-test/one/two/another.txt
    #- mc rm test/s3browser-test/one/two/three/another.txt
    - mc cp ./test/one.txt test/s3browser-test/1.1.0/
    - mc cp ./test/one.txt test/s3browser-test/1.1/
    - mc cp ./test/one.txt test/s3browser-test/1/
    - mc cp ./test/one.txt test/s3browser-test/1.2.0/
    - mc cp ./test/one.txt test/s3browser-test/1.2.0-dev/
    - mc cp ./test/one.txt test/s3browser-test/1.10.0/
    - mc cp ./test/one.txt test/s3browser-test/1.10/
    - mc cp ./test/one.txt test/s3browser-test/1.10.0-rc1/
    - mc cp ./test/one.txt test/s3browser-test/1.11.0/

  - name: compile-and-run
    image: golang:1.14-alpine
    environment:
      S3_SITENAME: "Test Site"
      S3_REGION: us-east-1
      S3_DEBUG: true
      S3_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_SECRET: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_ENDPOINT: objectstorage:9000
      S3_HOST: objectstorage
      S3_EXTRA: ":9000"
      S3_BUCKET: s3browser-test
      S3_SECURE: false
      S3_PROTO: http
      S3_REFRESH: 25s
      S3_REFRESH_SECRET: "secret"
      S3_SIGNED_URL_REDIRECT: true
      S3_SKIP_SERVING: true
      S3_SEMANTIC_SORT: true
      S3_ALLOW_CUSTOMIZATION: true
      GO111MODULE: on
    commands:
    - apk add wget mailcap ca-certificates gettext libintl curl git
    - mkdir -p /go/src/github.com/caddyserver/
    - git clone --branch v1.0.5 https://github.com/caddyserver/caddy.git /go/src/github.com/caddyserver/caddy
    - cd /go/src/github.com/caddyserver/caddy/caddy
    - sed -i '/This is where other plugins get plugged in (imported)/a _ "github.com/techknowlogick/caddy-s3browser"' caddymain/run.go
    - go mod edit -replace github.com/techknowlogick/caddy-s3browser=/drone/src
    - go install -v .
    - /go/bin/caddy -version
    - "envsubst < /drone/src/Caddyfile.tmpl > /drone/src/test/Caddyfile"
    - cat /drone/src/test/Caddyfile
    - /go/bin/caddy -conf /drone/src/test/Caddyfile &
    - sleep 6
    - "curl -v localhost"
    - "curl -v -H \"Accept: application/json\" localhost"
    - "curl -v -X POST 'api:$S3_REFRESH_SECRET@localhost'"

services:
- name: objectstorage
  image: minio/minio:RELEASE.2020-04-04T05-39-31Z
  command:
  - server
  - /data
  environment:
    MINIO_ACCESS_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    MINIO_BROWSER: off
    MINIO_SECRET_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
